name: Update Intranet Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON data to update'
        required: true
        type: string

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update data file
        run: |
          mkdir -p data
          echo '${{ github.event.inputs.data }}' > data/intranet-data.json
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/intranet-data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 Auto-update intranet data $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
